ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_mxn INT UNSIGNED NOT NULL DEFAULT 9900;
ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_days INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS plus_owned BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS marketing_email BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMP NULL;
CREATE TABLE IF NOT EXISTS billing_customers (
 user_id CHAR(32) PRIMARY KEY, stripe_id VARCHAR(100) NOT NULL UNIQUE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS billing_orders (
 id CHAR(32) PRIMARY KEY,user_id CHAR(32) NOT NULL,creator_id CHAR(32) NULL,
 kind ENUM('subscription','plus','tip') NOT NULL,amount INT UNSIGNED NOT NULL,trial_days INT NOT NULL DEFAULT 0,
 commission INT NOT NULL,label VARCHAR(120) NOT NULL,request_key VARCHAR(80) NOT NULL,
 stripe_session VARCHAR(100) NULL UNIQUE,stripe_subscription VARCHAR(100) NULL,
 status VARCHAR(30) NOT NULL DEFAULT 'created',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(user_id,request_key),INDEX(user_id,creator_id,status),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(creator_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS billing_subscriptions (
 stripe_id VARCHAR(100) PRIMARY KEY,order_id CHAR(32) NOT NULL,user_id CHAR(32) NOT NULL,creator_id CHAR(32) NOT NULL,
 status VARCHAR(30) NOT NULL,amount INT NOT NULL,period_end BIGINT NOT NULL DEFAULT 0,
 trial_end BIGINT NULL,cancel_at_end BOOLEAN NOT NULL DEFAULT 0,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(user_id,creator_id),FOREIGN KEY(order_id) REFERENCES billing_orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS billing_payments (
 charge_id VARCHAR(100) PRIMARY KEY,order_id CHAR(32) NOT NULL,invoice_id VARCHAR(100) NULL UNIQUE,
 gross INT NOT NULL,stripe_fee INT NULL,platform_fee INT NOT NULL,net INT NOT NULL DEFAULT 0,
 refunded INT NOT NULL DEFAULT 0,disputed BOOLEAN NOT NULL DEFAULT 0,available_at BIGINT NOT NULL DEFAULT 0,
 status VARCHAR(30) NOT NULL DEFAULT 'pending',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(order_id) REFERENCES billing_orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS billing_events (
 stripe_id VARCHAR(100) PRIMARY KEY,type VARCHAR(100) NOT NULL,processed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS billing_withdrawals (
 id CHAR(32) PRIMARY KEY,user_id CHAR(32) NOT NULL,amount INT NOT NULL,
 bank_data TEXT NOT NULL,bank_last4 CHAR(4) NOT NULL,bank_name VARCHAR(100) NOT NULL,
 status ENUM('pending','paid','rejected') NOT NULL DEFAULT 'pending',reference VARCHAR(150) NOT NULL DEFAULT '',
 note VARCHAR(500) NOT NULL DEFAULT '',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 reviewed_at TIMESTAMP NULL,reviewer_id CHAR(32) NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS billing_mail (
 id CHAR(32) PRIMARY KEY,user_id CHAR(32) NOT NULL,event_key VARCHAR(180) NOT NULL UNIQUE,
 subject VARCHAR(200) NOT NULL,body TEXT NOT NULL,url VARCHAR(500) NOT NULL,marketing BOOLEAN NOT NULL DEFAULT 0,
 attempts INT NOT NULL DEFAULT 0,sent_at TIMESTAMP NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
