name: Subir por SFTP automaticamente

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🎉 Deploy SFTP
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Descargando el codigo mas reciente
      uses: actions/checkout@v4
    
    - name: 📂 Subiendo archivos al servidor
      uses: appleboy/scp-action@master
      with:
        host: 'access-5021305806.webspace-host.com'
        username: 'su81402'
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        source: "."
        target: "/public/"