name: Subir por SFTP automaticamente

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🎉 Deploy SFTP
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Descargando el codigo
      uses: actions/checkout@v4
    
    - name: 📂 Subiendo por SFTP puro
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: access-5021305806.webspace-host.com
        username: su81402
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: sftp
        port: 22
        server-dir: /
        exclude: |
          **/.git*
          **/.git*/**